apiVersion: v1
kind: Service
metadata:
  name: smart-assistant
  namespace: smart-assistant
spec:
  selector:
    app: smart-assistant
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP